### ISSUE TITLE
Iteration 1 - Yotzimlilmod (OutToLearn) - MVP

### ISSUE THREAD

**Issue by katiapr** [katiapr/YotzimLilmod#57]
@ItamarShDev 

[our Iteration 1](https://github.com/katiapr/YotzimLilmod/wiki/Iteration-1---MVP)
[issues - link](https://github.com/katiapr/YotzimLilmod/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Iteration+1+-+MVP%22)

**Comment by ItamarShDev** [comment]
still missing iteration 2 planning
