### ISSUE TITLE
Iteration 2 - Yotzimlilmod (OutToLearn) - MVC

### ISSUE THREAD

**Issue by katiapr** [katiapr/YotzimLilmod#58]
@ItamarShDev 

[our iteration 2](https://github.com/katiapr/YotzimLilmod/wiki/Iteration-2----MVC)
[issues](https://github.com/katiapr/YotzimLilmod/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Iteration+2+%22)

**Comment by ItamarShDev** [comment]
missing testing reference
next iteration planning
