### ISSUE TITLE
SDS - YotzimLilmod(OutToLearn)

### ISSUE THREAD

**Issue by katiapr** [katiapr/YotzimLilmod#59]
@ItamarShDev 

[Our - SDS ](https://github.com/katiapr/YotzimLilmod/wiki/SDS)

**Comment by ItamarShDev** [comment]
Page still half empty. you're declaring diagrams that doesn't exists.
the info is lacking depth

**Comment by Lee-Bit** [comment]
please check our SDS  https://github.com/katiapr/YotzimLilmod/wiki/SDS

**Comment by robi-y** [comment]
Don't forget to assign our TA
