### ISSUE TITLE
Iteration 3 - Yotzimlilmod (OutToLearn) - Functionality

### ISSUE THREAD

**Issue by katiapr** [katiapr/YotzimLilmod#70]
@ItamarShDev 

[Issues Iteration 3](https://github.com/katiapr/YotzimLilmod/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Iteration+3%22)

[Iteration - 3](https://github.com/katiapr/YotzimLilmod/wiki/Iteration-3)

**Comment by ItamarShDev** [comment]
missing 
next iteration planning
testing reference

**Comment by Lee-Bit** [comment]
We added the missings, please check again.
