### ISSUE TITLE
Iteration 4 - Yotzimlilmod (OutToLearn)

### ISSUE THREAD

**Issue by katiapr** [katiapr/YotzimLilmod#71]
@ItamarShDev 

[Iteration - 4](https://github.com/katiapr/YotzimLilmod/wiki/Iteration-4)

[Iteration - 4 - Issues](https://github.com/katiapr/YotzimLilmod/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Iteration+4%22)

**Comment by ItamarShDev** [comment]
i guess this one is still WIP
